/**
 * PWA helpers: service-worker registration, the "Zur Startseite hinzufügen" prompt
 * and online/offline status.
 *
 * The worker itself is GENERATED by vite-plugin-pwa (`workbox generateSW`, emitted as
 * `dist/sw.js`, see apps/web/vite.config.ts). `injectRegister: false` there, so this
 * module owns registration — production only, because a service worker in front of the
 * vite dev server breaks HMR. The precache/navigation fallback never covers `/api` or
 * `/uploads`.
 */
import { useCallback, useEffect, useState } from "react";
import { readStorage, storageKeys, writeStorage } from "./storage";

/**
 * Registers the offline app shell. Only in production builds: a service worker in
 * front of the vite dev server breaks HMR.
 */
export function registerServiceWorker(): void {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;
  const isProduction = (import.meta.env as unknown as Record<string, unknown>).PROD === true;
  if (!isProduction) return;

  window.addEventListener("load", () => {
    void navigator.serviceWorker.register("/sw.js", { scope: "/" }).catch((error: unknown) => {
      console.warn("[pwa] Service Worker konnte nicht registriert werden:", error);
    });
  });
}

/** Chromium's install prompt event (not in lib.dom yet). */
export interface BeforeInstallPromptEvent extends Event {
  readonly platforms: readonly string[];
  prompt: () => Promise<void>;
  readonly userChoice: Promise<{ outcome: "accepted" | "dismissed"; platform: string }>;
}

const DISMISS_DAYS = 14;

export function isStandalone(): boolean {
  if (typeof window === "undefined") return false;
  const iosStandalone = (window.navigator as Navigator & { standalone?: boolean }).standalone;
  return window.matchMedia("(display-mode: standalone)").matches || iosStandalone === true;
}

/** iOS has no install prompt event — the UI must explain "Teilen → Zum Home-Bildschirm". */
export function isIosSafari(): boolean {
  if (typeof navigator === "undefined") return false;
  const ua = navigator.userAgent;
  const isIos = /iPad|iPhone|iPod/.test(ua) || (ua.includes("Macintosh") && "ontouchend" in document);
  const isSafari = /Safari/.test(ua) && !/CriOS|FxiOS|EdgiOS|OPiOS/.test(ua);
  return isIos && isSafari;
}

function dismissedRecently(): boolean {
  const raw = readStorage(storageKeys.installPromptDismissedAt);
  if (!raw) return false;
  const timestamp = Number.parseInt(raw, 10);
  if (Number.isNaN(timestamp)) return false;
  return Date.now() - timestamp < DISMISS_DAYS * 24 * 60 * 60 * 1000;
}

export interface InstallPromptState {
  /** True when the browser offered an install prompt (Chromium, Android). */
  canPrompt: boolean;
  /** True when the app is already installed / running standalone. */
  installed: boolean;
  /** True when only manual instructions are possible (iOS Safari). */
  needsManualInstructions: boolean;
  /** Should the banner be rendered at all? */
  shouldShow: boolean;
  /** Triggers the native prompt; resolves to true when the user accepted. */
  promptInstall: () => Promise<boolean>;
  /** Hides the banner for 14 days. */
  dismiss: () => void;
}

export function useInstallPrompt(): InstallPromptState {
  const [event, setEvent] = useState<BeforeInstallPromptEvent | null>(null);
  const [installed, setInstalled] = useState(() => isStandalone());
  const [dismissed, setDismissed] = useState(() => dismissedRecently());
  const [manual] = useState(() => isIosSafari());

  useEffect(() => {
    function onBeforeInstallPrompt(nativeEvent: Event) {
      nativeEvent.preventDefault();
      setEvent(nativeEvent as BeforeInstallPromptEvent);
    }
    function onInstalled() {
      setInstalled(true);
      setEvent(null);
    }
    window.addEventListener("beforeinstallprompt", onBeforeInstallPrompt);
    window.addEventListener("appinstalled", onInstalled);
    return () => {
      window.removeEventListener("beforeinstallprompt", onBeforeInstallPrompt);
      window.removeEventListener("appinstalled", onInstalled);
    };
  }, []);

  const promptInstall = useCallback(async () => {
    if (!event) return false;
    await event.prompt();
    const choice = await event.userChoice;
    setEvent(null);
    if (choice.outcome === "accepted") {
      setInstalled(true);
      return true;
    }
    writeStorage(storageKeys.installPromptDismissedAt, String(Date.now()));
    setDismissed(true);
    return false;
  }, [event]);

  const dismiss = useCallback(() => {
    writeStorage(storageKeys.installPromptDismissedAt, String(Date.now()));
    setDismissed(true);
  }, []);

  const canPrompt = event !== null;
  return {
    canPrompt,
    installed,
    needsManualInstructions: manual && !installed,
    shouldShow: !installed && !dismissed && (canPrompt || (manual && !installed)),
    promptInstall,
    dismiss,
  };
}

/** Live online/offline flag for the offline banner. */
export function useOnlineStatus(): boolean {
  const [online, setOnline] = useState(() =>
    typeof navigator === "undefined" ? true : navigator.onLine,
  );
  useEffect(() => {
    const goOnline = () => setOnline(true);
    const goOffline = () => setOnline(false);
    window.addEventListener("online", goOnline);
    window.addEventListener("offline", goOffline);
    return () => {
      window.removeEventListener("online", goOnline);
      window.removeEventListener("offline", goOffline);
    };
  }, []);
  return online;
}
