/**
 * PWA helpers: service-worker registration, the UPDATE policy, the
 * "Zur Startseite hinzufügen" prompt and online/offline status.
 *
 * The worker itself is GENERATED by vite-plugin-pwa (`workbox generateSW`, emitted as
 * `dist/sw.js`, see apps/web/vite.config.ts). `injectRegister: false` there, so this
 * module owns registration — production only, because a service worker in front of the
 * vite dev server breaks HMR. The precache/navigation fallback never covers `/api` or
 * `/uploads`.
 *
 * ## HOW AN UPDATE REACHES AN INSTALLED APP
 *
 * `skipWaiting` is off in the workbox config, so a newly installed worker WAITS instead
 * of claiming a document that is still running the old, code-split bundle. This module
 * is what lets it through:
 *
 *  1. **Notice it.** The browser only re-checks `sw.js` on navigation, and an installed
 *     iOS app navigates just once — at launch. Resuming it from the app switcher does
 *     not. So `update()` is called when the app becomes visible again, when the network
 *     comes back, and on a slow interval. That is what turns "kill the app twice" into
 *     "bring it to the foreground".
 *  2. **Decide.** With nothing unsaved on screen the swap happens immediately: that is
 *     the whole point, and the common case is a foreground check where a reload is
 *     invisible. With unsaved edits ({@link hasUnsavedWork}) it waits and
 *     `UpdateBanner` offers the reload, so a half-typed recipe is never discarded.
 *  3. **Swap.** `SKIP_WAITING` -> the worker activates -> `controllerchange` -> reload.
 *     Activation and reload therefore happen together, which matters because
 *     `cleanupOutdatedCaches` deletes the old precache on activate.
 *
 * A queued shopping-list mutation is not unsaved work: it is in IndexedDB and replays
 * after the reload (lib/persist.ts).
 */
import { useCallback, useEffect, useState, useSyncExternalStore } from "react";
import { readStorage, storageKeys, writeStorage } from "./storage";
import { hasUnsavedWork, subscribeUnsavedWork } from "./unsavedWork";

/* -------------------------------------------------------------------------- */
/* registration + updates                                                     */
/* -------------------------------------------------------------------------- */

/** How often to ask the server for a new `sw.js` while the app stays open. */
const UPDATE_POLL_MS = 30 * 60 * 1000;

let waiting: ServiceWorker | null = null;
/** An apply is in flight — do not start a second one. */
let applying = false;
/** The reload has been triggered; both signals below may fire, only one may act. */
let reloaded = false;
/** True when this document was already controlled at startup, i.e. not a first install. */
let hadController = false;
const updateListeners = new Set<() => void>();

/** A new version is installed and waiting for permission to take over. */
export function isUpdateReady(): boolean {
  return waiting !== null;
}

export function subscribeUpdate(listener: () => void): () => void {
  updateListeners.add(listener);
  return () => updateListeners.delete(listener);
}

function announce(worker: ServiceWorker | null): void {
  if (waiting === worker) return;
  waiting = worker;
  for (const listener of [...updateListeners]) listener();
  // Nothing to lose -> take it now. Re-checked whenever the dirty flag clears, so a
  // form that gets saved lets the pending update through without another prompt.
  if (waiting !== null && !hasUnsavedWork()) applyUpdate();
}

/**
 * Lets the waiting worker take over and reloads. Safe to call when nothing is waiting
 * (no-op) and safe to call twice (both the apply and the reload are guarded).
 *
 * Reloads on whichever REAL signal arrives first — `controllerchange` (wired up in
 * {@link registerServiceWorker}) or the worker reaching `activated`. Deliberately no
 * fallback timer: if the swap silently fails, staying on the old version is the safe
 * outcome. A blind reload would re-attempt the same failing swap on the next launch and
 * every launch after that, which is a boot loop the user cannot escape from.
 */
export function applyUpdate(): void {
  const worker = waiting;
  if (worker === null || applying) return;
  applying = true;
  worker.addEventListener("statechange", () => {
    if (worker.state === "activated") reloadOnce();
  });
  worker.postMessage({ type: "SKIP_WAITING" });
}

function reloadOnce(): void {
  if (typeof window === "undefined" || reloaded) return;
  reloaded = true;
  window.location.reload();
}

/**
 * Registers the offline app shell. Only in production builds: a service worker in
 * front of the vite dev server breaks HMR.
 */
export function registerServiceWorker(): void {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;
  const isProduction = (import.meta.env as unknown as Record<string, unknown>).PROD === true;
  if (!isProduction) return;

  hadController = navigator.serviceWorker.controller !== null;

  // A worker activating mid-session means the document is now controlled by a version
  // it was not built with, so it has to reload. Guarded on `hadController` because
  // `clientsClaim` fires this on a FIRST install too, where the precache matches what
  // is already running and a reload would be a pointless flash.
  navigator.serviceWorker.addEventListener("controllerchange", () => {
    if (!hadController) return;
    reloadOnce();
  });

  window.addEventListener("load", () => {
    void navigator.serviceWorker
      .register("/sw.js", { scope: "/" })
      .then((registration) => watchForUpdates(registration))
      .catch((error: unknown) => {
        console.warn("[pwa] Service Worker konnte nicht registriert werden:", error);
      });
  });
}

function watchForUpdates(registration: ServiceWorkerRegistration): void {
  // Left over from a previous session that chose not to reload.
  if (registration.waiting !== null && navigator.serviceWorker.controller !== null) {
    announce(registration.waiting);
  }

  registration.addEventListener("updatefound", () => {
    // No controller yet = first install, which is not an "update" to announce.
    if (navigator.serviceWorker.controller === null) return;
    // `?? waiting` and the eager `installed` check are for the race where the browser
    // has already moved the new worker on by the time this handler runs — then there is
    // no statechange left to hear and the update would go unnoticed until the next launch.
    const incoming = registration.installing ?? registration.waiting;
    if (incoming === null) return;
    if (incoming.state === "installed") {
      announce(incoming);
      return;
    }
    incoming.addEventListener("statechange", () => {
      if (incoming.state === "installed") announce(incoming);
    });
  });

  const check = () => {
    if (applying) return;
    void registration.update().catch(() => {
      /* offline or the server is down — the next check will do */
    });
  };

  document.addEventListener("visibilitychange", () => {
    if (document.visibilityState === "visible") check();
  });
  window.addEventListener("online", check);
  window.setInterval(check, UPDATE_POLL_MS);

  // A form that gets saved while an update is pending should let it through, without
  // the user having to find the banner again.
  subscribeUnsavedWork(() => {
    if (waiting !== null && !hasUnsavedWork()) applyUpdate();
  });
}

/**
 * Everything the UpdateBanner needs. `unsavedWork` is part of it because the banner only
 * ever appears when something IS unsaved — with a clean screen the update has already
 * been applied by the time React could render it.
 */
export function useAppUpdate(): { ready: boolean; unsavedWork: boolean; apply: () => void } {
  const ready = useSyncExternalStore(subscribeUpdate, isUpdateReady, () => false);
  const unsavedWork = useSyncExternalStore(subscribeUnsavedWork, hasUnsavedWork, () => false);
  return { ready, unsavedWork, apply: applyUpdate };
}

/** Chromium's install prompt event (not in lib.dom yet). */
export interface BeforeInstallPromptEvent extends Event {
  readonly platforms: readonly string[];
  prompt: () => Promise<void>;
  readonly userChoice: Promise<{ outcome: "accepted" | "dismissed"; platform: string }>;
}

const DISMISS_DAYS = 14;

export function isStandalone(): boolean {
  if (typeof window === "undefined") return false;
  const iosStandalone = (window.navigator as Navigator & { standalone?: boolean }).standalone;
  return window.matchMedia("(display-mode: standalone)").matches || iosStandalone === true;
}

/** iOS has no install prompt event — the UI must explain "Teilen → Zum Home-Bildschirm". */
export function isIosSafari(): boolean {
  if (typeof navigator === "undefined") return false;
  const ua = navigator.userAgent;
  const isIos = /iPad|iPhone|iPod/.test(ua) || (ua.includes("Macintosh") && "ontouchend" in document);
  const isSafari = /Safari/.test(ua) && !/CriOS|FxiOS|EdgiOS|OPiOS/.test(ua);
  return isIos && isSafari;
}

function dismissedRecently(): boolean {
  const raw = readStorage(storageKeys.installPromptDismissedAt);
  if (!raw) return false;
  const timestamp = Number.parseInt(raw, 10);
  if (Number.isNaN(timestamp)) return false;
  return Date.now() - timestamp < DISMISS_DAYS * 24 * 60 * 60 * 1000;
}

export interface InstallPromptState {
  /** True when the browser offered an install prompt (Chromium, Android). */
  canPrompt: boolean;
  /** True when the app is already installed / running standalone. */
  installed: boolean;
  /** True when only manual instructions are possible (iOS Safari). */
  needsManualInstructions: boolean;
  /** Should the banner be rendered at all? */
  shouldShow: boolean;
  /** Triggers the native prompt; resolves to true when the user accepted. */
  promptInstall: () => Promise<boolean>;
  /** Hides the banner for 14 days. */
  dismiss: () => void;
}

export function useInstallPrompt(): InstallPromptState {
  const [event, setEvent] = useState<BeforeInstallPromptEvent | null>(null);
  const [installed, setInstalled] = useState(() => isStandalone());
  const [dismissed, setDismissed] = useState(() => dismissedRecently());
  const [manual] = useState(() => isIosSafari());

  useEffect(() => {
    function onBeforeInstallPrompt(nativeEvent: Event) {
      nativeEvent.preventDefault();
      setEvent(nativeEvent as BeforeInstallPromptEvent);
    }
    function onInstalled() {
      setInstalled(true);
      setEvent(null);
    }
    window.addEventListener("beforeinstallprompt", onBeforeInstallPrompt);
    window.addEventListener("appinstalled", onInstalled);
    return () => {
      window.removeEventListener("beforeinstallprompt", onBeforeInstallPrompt);
      window.removeEventListener("appinstalled", onInstalled);
    };
  }, []);

  const promptInstall = useCallback(async () => {
    if (!event) return false;
    await event.prompt();
    const choice = await event.userChoice;
    setEvent(null);
    if (choice.outcome === "accepted") {
      setInstalled(true);
      return true;
    }
    writeStorage(storageKeys.installPromptDismissedAt, String(Date.now()));
    setDismissed(true);
    return false;
  }, [event]);

  const dismiss = useCallback(() => {
    writeStorage(storageKeys.installPromptDismissedAt, String(Date.now()));
    setDismissed(true);
  }, []);

  const canPrompt = event !== null;
  return {
    canPrompt,
    installed,
    needsManualInstructions: manual && !installed,
    shouldShow: !installed && !dismissed && (canPrompt || (manual && !installed)),
    promptInstall,
    dismiss,
  };
}

/** Live online/offline flag for the offline banner. */
export function useOnlineStatus(): boolean {
  const [online, setOnline] = useState(() =>
    typeof navigator === "undefined" ? true : navigator.onLine,
  );
  useEffect(() => {
    const goOnline = () => setOnline(true);
    const goOffline = () => setOnline(false);
    window.addEventListener("online", goOnline);
    window.addEventListener("offline", goOffline);
    return () => {
      window.removeEventListener("online", goOnline);
      window.removeEventListener("offline", goOffline);
    };
  }, []);
  return online;
}
